export const INDIAN_INGREDIENTS = [
  { name: 'Pyaaz (Onion)', emoji: '🧅', search: 'pyaaz onion' },
  { name: 'Tamatar (Tomato)', emoji: '🍅', search: 'tamatar tomato' },
  { name: 'Aloo (Potato)', emoji: '🥔', search: 'aloo potato' },
  { name: 'Paneer', emoji: '🧊', search: 'paneer' },
  { name: 'Dahi (Curd)', emoji: '🥛', search: 'dahi curd yogurt' },
  { name: 'Chawal (Rice)', emoji: '🍚', search: 'chawal rice' },
  { name: 'Atta (Flour)', emoji: '🌾', search: 'atta flour' },
  { name: 'Dal (Lentils)', emoji: '🫘', search: 'dal lentils' },
  { name: 'Jeera (Cumin)', emoji: '🌿', search: 'jeera cumin' },
  { name: 'Haldi (Turmeric)', emoji: '🟡', search: 'haldi turmeric' },
  { name: 'Mirch (Chili)', emoji: '🌶️', search: 'mirch chili' },
  { name: 'Adrak (Ginger)', emoji: '🫚', search: 'adrak ginger' },
  { name: 'Lehsun (Garlic)', emoji: '🧄', search: 'lehsun garlic' },
  { name: 'Palak (Spinach)', emoji: '🥬', search: 'palak spinach' },
  { name: 'Gobi (Cauliflower)', emoji: '🥦', search: 'gobi cauliflower' },
  { name: 'Matar (Peas)', emoji: '🫛', search: 'matar peas' },
  { name: 'Bhindi (Okra)', emoji: '🥒', search: 'bhindi okra' },
  { name: 'Baigan (Brinjal)', emoji: '🍆', search: 'baigan brinjal eggplant' },
  { name: 'Shimla Mirch', emoji: '🫑', search: 'shimla mirch capsicum bell pepper' },
  { name: 'Lauki (Bottle Gourd)', emoji: '🥒', search: 'lauki bottle gourd' },
  { name: 'Tori (Ridge Gourd)', emoji: '🥒', search: 'tori ridge gourd' },
  { name: 'Besan (Gram Flour)', emoji: '🌾', search: 'besan gram flour' },
  { name: 'Suji (Semolina)', emoji: '🌾', search: 'suji semolina' },
  { name: 'Maida', emoji: '🌾', search: 'maida' },
  { name: 'Bread', emoji: '🍞', search: 'bread' },
  { name: 'Egg', emoji: '🥚', search: 'egg anda' },
  { name: 'Chicken', emoji: '🍗', search: 'chicken' },
  { name: 'Mutton', emoji: '🍖', search: 'mutton' },
  { name: 'Fish', emoji: '🐟', search: 'fish' },
  { name: 'Prawns', emoji: '🍤', search: 'prawns' },
  { name: 'Milk', emoji: '🥛', search: 'milk doodh' },
  { name: 'Butter', emoji: '🧈', search: 'butter makkhan' },
  { name: 'Ghee', emoji: '🧈', search: 'ghee' },
  { name: 'Cream', emoji: '🥛', search: 'cream malai' },
  { name: 'Cheese', emoji: '🧀', search: 'cheese' },
  { name: 'Maggi', emoji: '🍜', search: 'maggi noodles' },
  { name: 'Pasta', emoji: '🍝', search: 'pasta' },
  { name: 'Noodles', emoji: '🍜', search: 'noodles' },
  { name: 'Soybean', emoji: '🫘', search: 'soybean' },
  { name: 'Rajma', emoji: '🫘', search: 'rajma kidney beans' },
  { name: 'Chole (Chickpeas)', emoji: '🫘', search: 'chole chickpeas' },
  { name: 'Moong Dal', emoji: '🫘', search: 'moong dal' },
  { name: 'Masoor Dal', emoji: '🫘', search: 'masoor dal' },
  { name: 'Chana Dal', emoji: '🫘', search: 'chana dal' },
  { name: 'Urad Dal', emoji: '🫘', search: 'urad dal' },
  { name: 'Coconut', emoji: '🥥', search: 'coconut nariyal' },
  { name: 'Lemon', emoji: '🍋', search: 'lemon nimbu' },
  { name: 'Pudina (Mint)', emoji: '🌿', search: 'pudina mint' },
  { name: 'Dhaniya (Coriander)', emoji: '🌿', search: 'dhaniya coriander' },
  { name: 'Curry Patta', emoji: '🌿', search: 'curry patta' },
  { name: 'Hing (Asafoetida)', emoji: '🧂', search: 'hing asafoetida' },
  { name: 'Garam Masala', emoji: '🧂', search: 'garam masala' },
  { name: 'Red Chili Powder', emoji: '🌶️', search: 'red chili powder' },
  { name: 'Dhania Powder', emoji: '🧂', search: 'dhania powder' },
  { name: 'Amchur', emoji: '🧂', search: 'amchur mango powder' },
  { name: 'Saunf (Fennel)', emoji: '🌿', search: 'saunf fennel' },
];

export const QUICK_ADD_INGREDIENTS = [
  { name: 'Pyaaz', emoji: '🧅' },
  { name: 'Tamatar', emoji: '🍅' },
  { name: 'Aloo', emoji: '🥔' },
  { name: 'Ghee', emoji: '🧈' },
  { name: 'Mirch', emoji: '🌶️' },
  { name: 'Adrak', emoji: '🫚' },
  { name: 'Lehsun', emoji: '🧄' },
  { name: 'Chawal', emoji: '🍚' },
  { name: 'Dal', emoji: '🫘' },
  { name: 'Doodh', emoji: '🥛' },
  { name: 'Paneer', emoji: '🧊' },
  { name: 'Anda', emoji: '🥚' },
];
