import React, { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { useNavigate } from 'react-router-dom';
import { 
  Plus, 
  Trash2, 
  Share2, 
  ShoppingCart, 
  CheckCircle2, 
  Circle, 
  ChevronRight,
  X,
  AlertCircle
} from 'lucide-react';
import { useAppStore, GroceryItem } from '../store';
import { cn } from '../lib/utils';

const CATEGORIES = [
  { id: 'veg', name: '🥬 Sabziyan (Vegetables)', icon: '🥬' },
  { id: 'grains', name: '🫘 Daalen & Grains', icon: '🫘' },
  { id: 'dairy', name: '🥛 Dairy', icon: '🥛' },
  { id: 'spices', name: '🧂 Masale & Others', icon: '🧂' },
  { id: 'others', name: '📦 Others', icon: '📦' }
];

// Mock data for initial view if empty
const MOCK_ITEMS: Omit<GroceryItem, 'id'>[] = [
  { name: 'Aloo (Potato)', quantity: '2 kg', category: '🥬 Sabziyan (Vegetables)', checked: false, price: 60 },
  { name: 'Pyaaz (Onion)', quantity: '1 kg', category: '🥬 Sabziyan (Vegetables)', checked: false, price: 40 },
  { name: 'Tamatar (Tomato)', quantity: '1 kg', category: '🥬 Sabziyan (Vegetables)', checked: false, price: 50 },
  { name: 'Shimla Mirch', quantity: '500g', category: '🥬 Sabziyan (Vegetables)', checked: false, price: 40 },
  { name: 'Palak (Spinach)', quantity: '2 bunch', category: '🥬 Sabziyan (Vegetables)', checked: false, price: 30 },
  { name: 'Moong Dal', quantity: '500g', category: '🫘 Daalen & Grains', checked: false, price: 80 },
  { name: 'Rajma', quantity: '500g', category: '🫘 Daalen & Grains', checked: false, price: 90 },
  { name: 'Chawal (Rice)', quantity: '2 kg', category: '🫘 Daalen & Grains', checked: false, price: 120 },
  { name: 'Doodh (Milk)', quantity: '2 litre', category: '🥛 Dairy', checked: false, price: 120 },
  { name: 'Dahi (Curd)', quantity: '500g', category: '🥛 Dairy', checked: false, price: 40 },
  { name: 'Paneer', quantity: '200g', category: '🥛 Dairy', checked: false, price: 80 },
  { name: 'Garam Masala', quantity: '1 packet', category: '🧂 Masale & Others', checked: false, price: 30 },
  { name: 'Jeera', quantity: '100g', category: '🧂 Masale & Others', checked: false, price: 25 },
];

export default function GroceryList() {
  const navigate = useNavigate();
  const { 
    groceryList, 
    toggleGroceryItem, 
    removeGroceryItem, 
    clearGroceryList,
    addGroceryItem 
  } = useAppStore();

  const [showAddModal, setShowAddModal] = useState(false);
  const [showClearConfirm, setShowClearConfirm] = useState(false);
  const [newItemName, setNewItemName] = useState('');
  const [newItemQty, setNewItemQty] = useState('');
  const [newItemCategory, setNewItemCategory] = useState('📦 Others');

  // Use mock data if list is empty for demonstration, otherwise use store data
  const displayList = useMemo(() => {
    if (groceryList.length === 0) {
      return MOCK_ITEMS.map((item, index) => ({ ...item, id: `mock-${index}` }));
    }
    return groceryList;
  }, [groceryList]);

  const checkedCount = displayList.filter(item => item.checked).length;
  const totalCount = displayList.length;
  const progress = totalCount > 0 ? (checkedCount / totalCount) * 100 : 0;
  
  const totalPrice = displayList.reduce((sum, item) => sum + (item.price || 0), 0);
  const minPrice = Math.floor(totalPrice * 0.9);
  const maxPrice = Math.ceil(totalPrice * 1.1);

  const groupedItems = useMemo(() => {
    const groups: Record<string, any[]> = {};
    displayList.forEach(item => {
      if (!groups[item.category]) groups[item.category] = [];
      groups[item.category].push(item);
    });
    return groups;
  }, [displayList]);

  const handleAddItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemName) return;
    addGroceryItem({
      name: newItemName,
      quantity: newItemQty || '1 unit',
      category: newItemCategory,
      price: Math.floor(Math.random() * 100) + 20 // Random price for mock feel
    });
    setNewItemName('');
    setNewItemQty('');
    setShowAddModal(false);
  };

  const shareOnWhatsApp = () => {
    const text = `🛒 *My GharKaKhana Grocery List*\n\n` + 
      displayList.map(item => `${item.checked ? '✅' : '☐'} ${item.name} (${item.quantity})`).join('\n') +
      `\n\nGenerated by GharKaKhana App`;
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
  };

  const orderOnBlinkit = () => {
    window.open('https://blinkit.com', '_blank');
  };

  return (
    <div className="min-h-screen bg-primary-bg pb-32">
      {/* HEADER */}
      <header className="px-5 pt-8 pb-6 flex justify-between items-end">
        <div>
          <h1 className="text-white text-[22px] font-display font-bold">Grocery List 🛒</h1>
          <p className="text-secondary-text text-sm">Meal plan ke hisaab se auto-generated</p>
        </div>
        <button 
          onClick={() => setShowClearConfirm(true)}
          className="text-red-400 text-sm font-bold mb-1"
        >
          Clear All
        </button>
      </header>

      <main className="px-5 space-y-6">
        {/* SMART SUMMARY CARD */}
        <section>
          <div className="accent-gradient p-5 rounded-2xl shadow-xl relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4 opacity-10">
              <ShoppingCart size={80} />
            </div>
            
            <div className="relative z-10">
              <div className="flex items-center gap-2 text-black/80 font-bold mb-3">
                <span>📊 Is hafte ka summary</span>
              </div>
              
              <div className="text-black font-display text-lg font-bold mb-1">
                Total items: {totalCount} | Estimated cost: ₹{minPrice}-{maxPrice}
              </div>
              
              <p className="text-black/60 text-xs font-medium mb-4">
                Based on your meal plan for {new Date().toLocaleDateString('en-IN', { month: 'long', day: 'numeric' })}
              </p>
              
              <div className="space-y-2">
                <div className="flex justify-between text-[11px] font-bold text-black/80 uppercase tracking-wider">
                  <span>Progress</span>
                  <span>{checkedCount}/{totalCount} items checked</span>
                </div>
                <div className="h-2 bg-black/10 rounded-full overflow-hidden">
                  <motion.div 
                    initial={{ width: 0 }}
                    animate={{ width: `${progress}%` }}
                    className="h-full bg-black/40"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* GROUPED GROCERY LIST */}
        <section className="space-y-8">
          {CATEGORIES.map(category => {
            const items = groupedItems[category.name] || [];
            if (items.length === 0) return null;

            return (
              <div key={category.id} className="space-y-3">
                <h2 className="text-[#999] text-[13px] font-bold uppercase tracking-widest px-1">
                  {category.name}
                </h2>
                
                <div className="space-y-1">
                  <AnimatePresence mode="popLayout">
                    {items.sort((a, b) => Number(a.checked) - Number(b.checked)).map((item) => (
                      <motion.div
                        layout
                        key={item.id}
                        initial={{ opacity: 0, x: -10 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, scale: 0.95 }}
                        className={cn(
                          "flex items-center gap-4 p-4 rounded-xl border transition-all",
                          item.checked 
                            ? "bg-white/[0.02] border-white/5 opacity-50" 
                            : "bg-[#141414] border-white/5"
                        )}
                        onClick={() => toggleGroceryItem(item.id)}
                      >
                        <button className="flex-shrink-0">
                          {item.checked ? (
                            <CheckCircle2 className="text-white" size={22} />
                          ) : (
                            <Circle className="text-white/20" size={22} />
                          )}
                        </button>
                        
                        <div className="flex-1 min-w-0">
                          <h3 className={cn(
                            "text-[15px] font-medium truncate",
                            item.checked ? "text-secondary-text line-through" : "text-white"
                          )}>
                            {item.name}
                          </h3>
                          <div className="flex items-center gap-2 text-[13px] text-secondary-text">
                            <span>{item.quantity}</span>
                            <span>•</span>
                            <span className="text-[#666]">₹{item.price}</span>
                          </div>
                        </div>

                        <button 
                          onClick={(e) => {
                            e.stopPropagation();
                            removeGroceryItem(item.id);
                          }}
                          className="text-white/10 hover:text-red-400 transition-colors p-1"
                        >
                          <Trash2 size={16} />
                        </button>
                      </motion.div>
                    ))}
                  </AnimatePresence>
                </div>
              </div>
            );
          })}
        </section>

        {/* BOTTOM ACTIONS */}
        <section className="pt-4 space-y-3">
          <button 
            onClick={orderOnBlinkit}
            className="w-full h-14 rounded-2xl border border-white/10 flex items-center justify-center gap-3 text-white font-bold text-[15px] hover:bg-white/5 transition-all"
          >
            <ShoppingCart size={20} />
            🛒 Blinkit pe Order Karo
          </button>
          
          <button 
            onClick={shareOnWhatsApp}
            className="w-full h-14 rounded-2xl bg-white/5 flex items-center justify-center gap-3 text-white font-bold text-[15px] hover:bg-white/10 transition-all"
          >
            <Share2 size={20} />
            📤 List Share Karo
          </button>
        </section>
      </main>

      {/* FLOATING ADD BUTTON */}
      <motion.button
        whileHover={{ scale: 1.1 }}
        whileTap={{ scale: 0.9 }}
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-24 right-6 w-14 h-14 rounded-full accent-gradient flex items-center justify-center text-black shadow-2xl z-40"
      >
        <Plus size={28} />
      </motion.button>

      {/* ADD ITEM MODAL */}
      <AnimatePresence>
        {showAddModal && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center px-6">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowAddModal(false)}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm"
            />
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              className="relative w-full max-w-sm bg-[#1A1A1A] border border-white/10 rounded-3xl p-6 shadow-2xl"
            >
              <h2 className="text-white text-xl font-display font-bold mb-6">Naya Item Add Karo</h2>
              
              <form onSubmit={handleAddItem} className="space-y-4">
                <div className="space-y-2">
                  <label className="text-[#666] text-xs font-bold uppercase tracking-wider px-1">Item ka naam</label>
                  <input 
                    autoFocus
                    type="text" 
                    value={newItemName}
                    onChange={(e) => setNewItemName(e.target.value)}
                    placeholder="e.g. Bread, Eggs..."
                    className="w-full h-12 bg-white/5 border border-white/10 rounded-xl px-4 text-white outline-none focus:border-white/20 transition-all"
                  />
                </div>
                
                <div className="space-y-2">
                  <label className="text-[#666] text-xs font-bold uppercase tracking-wider px-1">Quantity</label>
                  <input 
                    type="text" 
                    value={newItemQty}
                    onChange={(e) => setNewItemQty(e.target.value)}
                    placeholder="e.g. 1 packet, 2 kg..."
                    className="w-full h-12 bg-white/5 border border-white/10 rounded-xl px-4 text-white outline-none focus:border-white/20 transition-all"
                  />
                </div>

                <div className="space-y-2">
                  <label className="text-[#666] text-xs font-bold uppercase tracking-wider px-1">Category</label>
                  <div className="flex flex-wrap gap-2">
                    {CATEGORIES.map(cat => (
                      <button
                        key={cat.id}
                        type="button"
                        onClick={() => setNewItemCategory(cat.name)}
                        className={cn(
                          "px-3 py-2 rounded-lg border text-[11px] font-bold transition-all",
                          newItemCategory === cat.name 
                            ? "accent-gradient text-black border-transparent" 
                            : "bg-white/5 border-white/5 text-white/40"
                        )}
                      >
                        {cat.name.split(' ')[0]}
                      </button>
                    ))}
                  </div>
                </div>

                <div className="flex gap-3 pt-4">
                  <button 
                    type="button"
                    onClick={() => setShowAddModal(false)}
                    className="flex-1 h-12 rounded-xl bg-white/5 text-white font-bold text-sm"
                  >
                    Cancel
                  </button>
                  <button 
                    type="submit"
                    className="flex-1 h-12 rounded-xl accent-gradient text-black font-bold text-sm"
                  >
                    Add Item
                  </button>
                </div>
              </form>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* CLEAR CONFIRMATION MODAL */}
      <AnimatePresence>
        {showClearConfirm && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center px-6">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setShowClearConfirm(false)}
              className="absolute inset-0 bg-black/80 backdrop-blur-sm"
            />
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              className="relative w-full max-w-sm bg-[#1A1A1A] border border-white/10 rounded-3xl p-6 shadow-2xl text-center"
            >
              <div className="w-16 h-16 bg-red-500/10 rounded-full flex items-center justify-center text-red-500 mx-auto mb-4">
                <AlertCircle size={32} />
              </div>
              <h2 className="text-white text-xl font-display font-bold mb-2">Poori list clear karein?</h2>
              <p className="text-secondary-text text-sm mb-8">Yeh action wapas nahi liya ja sakta.</p>
              
              <div className="flex gap-3">
                <button 
                  onClick={() => setShowClearConfirm(false)}
                  className="flex-1 h-12 rounded-xl bg-white/5 text-white font-bold text-sm"
                >
                  Nahi
                </button>
                <button 
                  onClick={() => {
                    clearGroceryList();
                    setShowClearConfirm(false);
                  }}
                  className="flex-1 h-12 rounded-xl bg-red-500 text-white font-bold text-sm"
                >
                  Haan, Clear Karo
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </div>
  );
}
